"""Domain enumerations shared by every layer of Vaynex.

All enums are ``StrEnum`` so they serialise to plain strings in JSON and are
stored as VARCHAR values in PostgreSQL (non-native enums keep migrations simple).
"""

from __future__ import annotations

from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class OrganizationType(StrEnum):
    MUNICIPAL = "MUNICIPAL"
    HEALTHCARE = "HEALTHCARE"
    POWER_UTILITY = "POWER_UTILITY"
    WATER_UTILITY = "WATER_UTILITY"
    TELECOM = "TELECOM"
    EMERGENCY_SERVICES = "EMERGENCY_SERVICES"
    TRANSPORT = "TRANSPORT"
    OTHER = "OTHER"


class InfrastructureType(StrEnum):
    POWER_PLANT = "POWER_PLANT"
    POWER_SUBSTATION = "POWER_SUBSTATION"
    HOSPITAL = "HOSPITAL"
    WATER_TREATMENT = "WATER_TREATMENT"
    WATER_PIPELINE = "WATER_PIPELINE"
    TELECOM_TOWER = "TELECOM_TOWER"
    ROAD = "ROAD"
    BRIDGE = "BRIDGE"
    SCHOOL = "SCHOOL"
    DATA_CENTER = "DATA_CENTER"
    EMERGENCY_CENTER = "EMERGENCY_CENTER"


class InfrastructureStatus(StrEnum):
    OPERATIONAL = "OPERATIONAL"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    MAINTENANCE = "MAINTENANCE"


class Criticality(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ServiceType(StrEnum):
    EMERGENCY_HEALTHCARE = "EMERGENCY_HEALTHCARE"
    HEALTHCARE = "HEALTHCARE"
    POWER_SUPPLY = "POWER_SUPPLY"
    WATER_SUPPLY = "WATER_SUPPLY"
    TELECOMMUNICATIONS = "TELECOMMUNICATIONS"
    EMERGENCY_COMMUNICATIONS = "EMERGENCY_COMMUNICATIONS"
    EMERGENCY_RESPONSE = "EMERGENCY_RESPONSE"
    TRANSPORTATION = "TRANSPORTATION"
    PUBLIC_EDUCATION = "PUBLIC_EDUCATION"
    DATA_SERVICES = "DATA_SERVICES"
    PUBLIC_SAFETY = "PUBLIC_SAFETY"
    OTHER = "OTHER"


class ServiceStatus(StrEnum):
    OPERATIONAL = "OPERATIONAL"
    DEGRADED = "DEGRADED"
    DISRUPTED = "DISRUPTED"
    SUSPENDED = "SUSPENDED"


class DependencyType(StrEnum):
    POWER = "POWER"
    WATER = "WATER"
    TELECOM = "TELECOM"
    TRANSPORT = "TRANSPORT"
    DATA = "DATA"
    OPERATIONAL = "OPERATIONAL"
    SERVICE_DELIVERY = "SERVICE_DELIVERY"


class DependencyStrength(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EventType(StrEnum):
    POWER_FAILURE = "POWER_FAILURE"
    WATER_DISRUPTION = "WATER_DISRUPTION"
    TELECOM_OUTAGE = "TELECOM_OUTAGE"
    FLOOD = "FLOOD"
    EQUIPMENT_FAILURE = "EQUIPMENT_FAILURE"
    CYBER_INCIDENT = "CYBER_INCIDENT"
    FIRE = "FIRE"
    EARTHQUAKE = "EARTHQUAKE"
    TRAFFIC_DISRUPTION = "TRAFFIC_DISRUPTION"
    SENSOR_ALERT = "SENSOR_ALERT"
    OTHER = "OTHER"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(StrEnum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    MITIGATING = "MITIGATING"
    RESOLVED = "RESOLVED"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecommendationPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecommendationSource(StrEnum):
    RULE_ENGINE = "RULE_ENGINE"
    AI = "AI"


class RecommendationStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"


class AuditAction(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    ORGANIZATION_CREATED = "ORGANIZATION_CREATED"
    INFRASTRUCTURE_CREATED = "INFRASTRUCTURE_CREATED"
    INFRASTRUCTURE_UPDATED = "INFRASTRUCTURE_UPDATED"
    INFRASTRUCTURE_DELETED = "INFRASTRUCTURE_DELETED"
    SERVICE_CREATED = "SERVICE_CREATED"
    SERVICE_UPDATED = "SERVICE_UPDATED"
    DEPENDENCY_CREATED = "DEPENDENCY_CREATED"
    EVENT_CREATED = "EVENT_CREATED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_UPDATED = "INCIDENT_UPDATED"
    RISK_CALCULATED = "RISK_CALCULATED"
    AI_ANALYSIS_CREATED = "AI_ANALYSIS_CREATED"
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"
    RECOMMENDATION_ACCEPTED = "RECOMMENDATION_ACCEPTED"
    RECOMMENDATION_REJECTED = "RECOMMENDATION_REJECTED"
    RECOMMENDATION_COMPLETED = "RECOMMENDATION_COMPLETED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    SIMULATION_RUN = "SIMULATION_RUN"


class EntityKind(StrEnum):
    """Node kinds in the dependency graph."""

    INFRASTRUCTURE = "INFRASTRUCTURE"
    SERVICE = "SERVICE"


class ImpactRelationship(StrEnum):
    """How an asset came to be affected by an event."""

    ORIGIN = "ORIGIN"
    DIRECT_EXPOSURE = "DIRECT_EXPOSURE"
    DEPENDENCY = "DEPENDENCY"
    HOSTED_SERVICE = "HOSTED_SERVICE"


class SimulationScenario(StrEnum):
    HOSPITAL_POWER_FAILURE = "hospital_power_failure"
    WATER_SUPPLY_DISRUPTION = "water_supply_disruption"
    TELECOM_OUTAGE = "telecom_outage"
    FLOOD_INFRASTRUCTURE_RISK = "flood_infrastructure_risk"
